name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装依赖 & 构建
        run: |
          npm install
          npm run build

      - name: 安装腾讯云依赖
        run: |
          sudo pip install coscmd

      - name: 配置腾讯云依赖
        env:
          SECRET_ID: ${{ secrets.TCLOUD_API_ID }}
          SECRET_KEY: ${{ secrets.TCLOUD_API_KEY }}
          BUCKET: ${{ secrets.TCLOUD_BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: |
          coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: 上传到腾讯云COS
        run: |
          coscmd upload -rfs --delete ./dist/ /
